### ISSUE TITLE
[Discusión] Ejercicios: nomenclatura y reglas

### ISSUE THREAD

**Issue by chekos** [tacosdedatos/100DiasDeData#9]
## El asunto a discutir
Igual que en #8, la definición de lo que es un **ejercicio** y un **proyecto** fue decidida solo por mí pero para que esto funcione se necesita tener una discusión de varias personas. Igual con la definición de _niveles_ para describir cada **ejercicio**.  

A aprobar o modificar:
- [x] Nomenclatura: ¿Qué es un ejercicio? ¿Qué es un proyecto?
- [x] Reglas a seguir
- [x] Definición de niveles para ejercicios (los 3 dígitos)

### _Issues_ relacionados
#4, #8 

### Posibles soluciones
Solución 1: Se mantiene como esta el repositorio, definiciones y reglas.
Solución 2: Si se encuentra que estas directrices no son claras o efectivas, se hacen las modificaciones necesarias.

### Contexto adicional
Todo esto se encuentra en el README.
#### Definición de ejercicio y proyecto
* Un <span style="background-color:#c7a02278">ejercicio</span> es una actividad con una meta definida que puedes lograr en menos de una hora. No todos los ejercicios van a necesitar de escribir código para lograr la meta. Por ejemplo, crear unas paletas de color divergentes y secuenciales. Esto puede lograrse programáticamente escribiendo código o también utilizando ciertos sitios web.
* Un <span style="background-color:#be89ff78">proyecto</span> es un grupo de ejercicios relacionados. Estos llevan más de una hora en terminar y puede que los ejercicios que lo compongan sean secuenciales. Es decir, puede que el tercer ejercicio de un proyecto no pueda llevarse a cabo hasta que se termine el segundo ejercicio.

#### Reglas a seguir
* Un ejercicio no puede necesitar más de una hora en completarse. 
* Un ejercicio debe tener una meta que sea
  - Específica, Medible, Lograble, Relevante y con tiempo límite (una hora) o  _SMART_ por sus siglas en inglés (**S**pecific, **M**easurable, **A**chievable, **R**elevant, **T**ime-bound) 
* La meta de un ejercicio debe estar relacionada a el manejo, distribución, análisis, visualización, creación, consumo, entre otras cosas, de los datos.
* La meta de un ejercicio también puede ser relacionada a habilidades, responsabilidades y/o actividades relacionadas a los datos. Por ejemplo, un ejercicio pidiendo que unx lea un artículo sobre ética del uso de datos personales y escriba 300-500 palabras al respecto es válido. 
* Todos los datos necesarios para cumplir un ejercicio deben ser abiertos y accesibles para el público en general.
* Se pueden escribir ejercicios para software cerrado (como `Stata` y `SAS`). No sugieras que paguen por ese software. 
* Al igual que un ejercicio, un proyecto debe tener una meta _SMART_.
* Los ejercicios que componen un proyecto deben estar relacionados a la meta del proyecto. 

#### Sobre los 3 dígitos que describen el nivel del ejercicio:
El nivel de un ejercicio se describe en 3 áreas: **complejidad**, **nivel de conocimiento previo necesario**, **tiempo necesario**. 

Cada área recibe una calificación del 1 - 5. 

La **complejidad** de un ejercicio se define por el número de pasos y tecnologías necesarias para llevarlo a cabo. Por ejemplo, un ejercicio en el que aprendemos a crear un gráfico de barras con `bokeh` puede ser nivel 1 o 2 de complejidad ya que es una sola tecnología (`bokeh`) y son pocos pasos necesarios para crear un gráfico de barras. Sin embargo, si el ejercicio es personalizar un gráfico de barras con`bokeh`, puede que el nivel de complejidad suba, dependiendo en que tantos pasos requiera esta personalización. 

El **nivel de conocimiento previo necesario** depende de la cantidad de tecnologías y/o información necesaria para llevar a cabo el ejercicio sin ayuda de alguien más. Por ejemplo, un ejercicio donde aprendamos a crear buenos mapas puede que se concentre en escoger buenos colores o la proyección "correcta". Si este es el caso, el ejercicio asume que ya sabes crear un mapa (aunque sea básico). Si esto es lo único que se necesita saber previamente a comenzar el ejercicio, puede tener una calificación de 1 o 2 para esta área. (Un ejemplo de nivel 4 o 5 puede ser desplegar una aplicación shiny a un servidor, por ejemplo). 

El **tiempo necesario** depende de la cantidad mínima necesaria de tiempo para completar un ejercicio. Por ejemplo, un ejercicio rápido mostrando como hacer un `INNER JOIN` en SQL puede ser un nível 1 o 2, si el ejercicio requiere que creemos una cuenta de BigQuery para ejecutar este SQL con los datos en la nube esta área sería un 2 o 3 o 4. Si el ejercicio requiere crear y entrenar un modelo de aprendizaje automatizado con una cantidad enorme de datos puede que te tome la hora entera. Esto sería un 5.

**Comment by alanbato** [comment]
Estoy deacuerdo con que se tengan ejercicios y proyectos, pero yo propondria que se expanda la definicion de la siguiente manera:

* Un ejercicio, ademas de requerir menos tiempo para ser realizado, debe tocar solamente 1 (o 2) "temas" relacionado con los datos. Por ejemplo: recoleccion, limpieza, visualizacion, aprendizaje. Las demas partes deben o ser incluidas como parte del planteamiento (como un notebook con celdas pre-llenadas) o simplemente no consideradas.

* Por otro lado, un proyecto es todo aquel que requiera que el participante realize 2,3 o mas "temas" de los previamente mencionados. De esta manera, pudiera considerarse un proyecto aquel que va desde obtener los datos de un sitio web hasta realizar una visualizacion que cumpla con el objetivo del proyecto.


En cuanto al tema de como definir las metas u objetivos del un ejercicio o proyecto, creo deberiamos de tener definido de manera objetiva cual es el "resultado" que esperamos del ejercicio, a fin de que el participante pueda validar su solucion contra la que presentamos nosotros como "respuesta correcta". Aunque un ejercicio pudiera tener varias formas de resolverse o ser "abierto", creo que es bueno que el participante tenga una sensacion de logro al ver que le "salio bien" y para eso hay que definir que es lo que esperamos especificamente.

Habiendo dicho esto, en una clase de visualizacion de datos que tome durante la carrera, tuvimos varios ejercicios donde habia que analizar y visualizar la informacion, y si bien cada equipo era libre de tomar un camino diferente a como analizaba los datos, siempre se nos hacian "preguntas" acerca de la informacion que nos daban, con tal de corroborar que todos llegaramos a las mismas conclusiones. Creo que seria buena idea que los ejercicios/proyectos tengan tambien un par de preguntas que tengan una respuesta "correcta". Al estilo de:

* Cual es el X que mas Y en el periodo de Z-W
* Que tipo de distribucion tiene la variable A
* Dada esta informacion historica, realiza un modelo que prediga el valor B dados los datos C,D,E
* Y asi...

En cuanto a la manera de medir la "dificultad", considero que es un problema dificil hahaha. Las 3 variables estan relacionadas entre si... optaria por tener un solo valor que represente una mezcla de las 3. Por otro lado, considero que tener una escala de 1 a 5 hace que sea mas dificil que los que desarrollen los ejercicios tengan un concenso claro, lo que yo puedo considerar un 3 tal vez para ti es un 4, y lo que para mi es un 4 para ti es un 3 y para otro un 5. Si se buscara que fuera una escala lo haria de 3 valores como Basico-Intermedio-Avanzado. Estos serian mas faciles de definir claramente donde termina uno y empieza el otro.

Si llegaste hasta aqui deja un emoji de que lo leiste, enhorabuena :+1:

**Comment by Andrea-Monserrat** [comment]
Concuerdo con definir la escala en tres, porque me parece que puede haber ambiguedades al ser cinco (incluso sería bonito definirlas tipo semáforo).

**Comment by chekos** [comment]
Creo que debí haber separado esto en 3 issues jajaja

#### Sobre las definiciones de ejercicios y proyectos:
* Un ejercicio es una actividad con una meta definida que puedes lograr en menos de una hora. No todos los ejercicios van a necesitar de escribir código para lograr la meta. Por ejemplo, crear unas paletas de color divergentes y secuenciales. Esto puede lograrse programáticamente escribiendo código o también utilizando ciertos sitios web. **Un ejercicio debe tocar solamente 1 (o 2) "temas" relacionado con los datos. Por ejemplo: recoleccion, limpieza, visualización, aprendizaje. Las demás partes deben o ser incluidas como parte del planteamiento (como un notebook con celdas pre-llenadas) o simplemente no consideradas**
* Un proyecto es un grupo de ejercicios relacionados. Los proyectos toman más de una hora en terminar y puede que los ejercicios que lo compongan sean secuenciales. Es decir, puede que el tercer ejercicio de un proyecto no pueda llevarse a cabo hasta que se termine el segundo ejercicio. **Si tienes una idea de un ejercicio que toque más de 2 "temas", considera _romperlo_ en 2 o más ejercicios modulares para crear un proyecto en su lugar.**

#### Sobre las metas:
Concuerdo que debemos pedir que se incluya una manera de validar el cumplimiento de una meta. No todas las metas tienen una "respuesta correcta" pero debe incluirse en la plantilla a seguir (`instrucciones.md`) una sección de preguntas para medir el éxito del ejercicio.

En las reglas a seguir se podría incluir:
* Un ejercicio debe tener una meta que sea
  - Específica, Medible, Lograble, Relevante y con tiempo límite (una hora) o _SMART_ por sus siglas en inglés (**S**pecific, **M**easurable, **A**chievable, **R**elevant, **T**ime-bound)
  - **No todas las metas tienen una "respuesta correcta" siempre pero todas las metas tienen una manera de medir el éxito o la falla de la misma. En el archivo `instrucciones.md` se debe incluir algunas preguntas que quien realice el ejercicio pueda responder para medir si cumplió o no con el objetivo del ejercicio.**

#### Sobre los níveles:
Concuerdo que es más fácil que sea 1-3-5 y eso quedaría perfecto para algo estilo semáforo también. Yo creo que podríamos pedir que se califiquen del entre 1-3-5 las 3 dimensiones y en el momento de revisión de la propuesta se puede tener una discusión si es que se cree que alguna dimensión es más un 4 que un 3 o 5. Es decir, por default se puede ser 1-3-5 pero no es imposible tener un 2 o 4. Solo se necesita tener una discusión sobre ello.

El lenguaje se cambiaría de _Cada área recibe una calificación del 1 - 5._ a _Cada área recibe una calificación 1, 3 o 5 (Básico, intermedio, avanzado). Si tienes dudas de que nível darle a tu ejercicio sólo hace falta mencionarlo en tu PR y te ayudaremos a decidir._

**Comment by chekos** [comment]
like a este comentario si concuerdan con los cambios de la sección **Sobre las definiciones de ejercicios y proyectos**

**Comment by chekos** [comment]
like a este comentario si concuerdan con los cambios de la sección **Sobre las metas**

**Comment by chekos** [comment]
like a este comentario si concuerdan con los cambios de la sección **Sobre los níveles**
